#server:
#  port: 9000
#
#spring:
#  main:
#    web-application-type: reactive
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#
#
##eureka:
##  client:
##    serviceUrl:
##      defaultZone: http://localhost:8761/eureka
##    register-with-eureka: true
##    fetch-registry: true
##  instance:
##    prefer:
##      IpAddress: true
##    hostname: localhost
#
#
